### ISSUE TITLE
Merge Palo Alto into SF

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#236]
All PA TTs + hosts are on http://teawithstrangers.com/cities/sf, so we want to eliminate the Palo Alto city, but before doing so, we want to migrate all PA sign ups to SF. However, it'd be good to earmark them as PA, as we do some PA-specific targeting for emails and whatnot. 

@nickbarnwell we spoke about dividing cities into neighborhoods, and I'm not sure where that is in the pipeline atm. Would earmarking PA be simple? Or would it require a full build-out of this geographic hierarchy feature set?

**Comment by nickbarnwell** [comment]
Just going to assume this is done.
