### ISSUE TITLE
Organize /admin/overview/hosts

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#250]
Information should include only date not time or location
Should sort tables by city instead of having one big table of all hosts 
Should also be organized from most recent tea host to oldest tea host (in terms of last time they've hosted, not when they became a host)

**Comment by mehulkar** [comment]
I think we should expose a couple more API endpoints and make this page in client side javascript. We don't need to add in a fancy framework or anything, just jQuery will work since it's just a static page. @nickbarnwell any objections?

**Comment by nickbarnwell** [comment]
nope.
