### ISSUE TITLE
"Schedule Teatime" should say "Attend Teatime"

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#285]
It's confusing because when I read "Schedule", I interpret it as an action item for myself and I think it means that i should host one.

**Comment by mehulkar** [comment]
@ankitshah811 thoughts on this?

**Comment by ankitshah811** [comment]
you're right. can we make it 'Join for Tea Time'?

**Comment by mehulkar** [comment]
doesn't that sounds even more awkward than "Schedule Tea Time"? Do you mean _Join Tea Time_?

**Comment by ankitshah811** [comment]
Tea Time ≠ an organization or entity
I guess 'Join a Tea Time' is most appropriate, but that's feels awkward as a CTA
'Attend' is rubbing me as boring and functional
But then again, so does 'Schedule'
Let's go with 'Attend' and rethink this if needed down the road

**Comment by mehulkar** [comment]
Is the purpose of the button to create an account or to sign up for a slot at a tea time event?

**Comment by ankitshah811** [comment]
Sign up for a tea time slot. The button is diff when you're logged in vs. logged out

Create an account button is only visible WITH the form to create an account (i.e. Name + Email + CTA)

**Comment by mehulkar** [comment]
"Let's Get Tea" is the new CTA. This is no longer relevant.
