### ISSUE TITLE
Banner are different sizes on different pages

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#289]
Schedule page and cities (home) page have different sizes for the banner. When you transition, the change is too abrupt:

http://www.teawithstrangers.com/cities/SF/schedule
http://www.teawithstrangers.com/#cities

**Comment by nickbarnwell** [comment]
There is also the problem of "City Page Cover Photos are set via CSS in <head>; they are not changed when user navigates and Turbolinks are enabled".

Really we need to completely revamp the banners and how they're implemented. The current solution sucks and the CSS is janky

**Comment by nickbarnwell** [comment]
Fixed by new site!!
