### ISSUE TITLE
"Yes, you" link should be separate page

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#291]
Right now "Yes, you" on the home page links to the #footer of the page. The footer is pretty long. There are a few problems with this design:

1. Most other links lead to new pages. This one scrolls down. (consistency problem)
1. Footer sections are usually associated with nav and other boring stuff

proposed solutions:

1. put this section under Profile page. It makes sense that TWS takes the to put a consistent message in everyone's profile page (the place where they edit their own details). As a user, now when I go to the page where I define my profile, I now get a pre-filled preset. I realize that it's static/hardcoded. I realize that every other use has this on their profile. I realize that I'm part of a community, even though I'm an individual.
  - I think this is a nice idea, but it's a new design concept that I haven't seen before, so it might cause confusion. 

1. Make a new page and put it up on nav bar. Safe, standard. Puts important information in a well defined space.

**Comment by nickbarnwell** [comment]
Also closed by new design
