### ISSUE TITLE
Don't hyperlink to HONY and Upworthy

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#294]
Hyperlinks in the core dialogue of a website are distracting. You don't want a user to click away when they're reading this. Knowing what HONY and Upworthy are is _not_ a prerequisite to finishing reading the paragraph. The hyperlink also draws too much attention visually.

**Comment by nickbarnwell** [comment]
Fixed by new homepage. Woo!
