### ISSUE TITLE
'Nevermind' in tea time registration dialogue should go back to schedule

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#298]
Right now, it does nothing. Used to serve as 'close modal' button, but now we don't do modals

**Comment by nickbarnwell** [comment]
We do on desktop unless you changed something?

**Comment by ankitshah811** [comment]
I thought you changed it. I haven't seen a modal in months

**Comment by nickbarnwell** [comment]
My b. I merged a PR wrong. Fixed in 5e7fbc
