### ISSUE TITLE
tws-styles should be a gem, not a submodule

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#343]
Submodules suck and no one likes using them. gems for asset pipeline also suck and no one likes using them either. But if we _must_ have styles in a separate repo, a gem would be easier to manage git (for people who are less proficient in git).

Which calls to question, why do styles need to live in a seprate project at all?

**Comment by nickbarnwell** [comment]
Style that are shared globally amongst multiple TWS projects. We're one pull request away from having the blog match the updated website, or building the admin backend in a completely separate project that share a core brand identity.
