### ISSUE TITLE
/:city page should have schedule

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#349]
Stuff from this page: http://www.teawithstrangers.com/cities/SF/schedule

should show up on: http://www.teawithstrangers.com/SF

yes/no @ankitshah811 ?

**Comment by mehulkar** [comment]
ping

**Comment by ankitshah811** [comment]
they should for users that aren't waitlisted. this should be part of an active city page redesign push —

1. redesign host pages
2. redesign schedule partial
3. redesign confirm tea time modals
4. redesign everything a current user sees in `/profile` to be new aesthetic

**Comment by mehulkar** [comment]
pretty much done.
