### ISSUE TITLE
Typefaces from TypeKit are broken

### ISSUE THREAD

**Issue by nickbarnwell** [TeaWithStrangers/tws-on-rails#352]
Tested in FF/IE/Chrome and Gibson isn't being loaded at all. Regression due to #344?

**Comment by markbao** [comment]
Working for me on Chrome OS X and Safari OS X, but broken on Safari iOS. Curious.

**Comment by ankitshah811** [comment]
@mehulkar @markbao @nickbarnwell any idea how we might be able to fix this? kinda fugs

**Comment by ankitshah811** [comment]
@mehulkar bump

**Comment by mehulkar** [comment]
i'll look into this today. will need time with you to figure out what is
broken though. Site looks fine to me.


------
Mehul Kar
@mehulkar

**Comment by ankitshah811** [comment]
what the site looks like:

![img_0020](https://cloud.githubusercontent.com/assets/1022843/7755031/0cd3444a-ffa6-11e4-889f-1b603a6589b4.PNG)

what the site **should** look like:
![screenshot 2015-05-21 10 42 28](https://cloud.githubusercontent.com/assets/1022843/7755035/1e787cce-ffa6-11e4-8559-b2488747a2e2.png)

**Comment by ankitshah811** [comment]
ugh looking at them side by side pains me even more

**Comment by mehulkar** [comment]
Sorry for being obtuse, but can you point out which pieces are different? I
really can't tell the difference between the typefaces except that the
first seems larger and has more weight. Is it a completely different
typeface? or a different font-size / font-weight?


------
Mehul Kar
@mehulkar

**Comment by ankitshah811** [comment]
Sorry for being assumptive. All the fonts on the top are in a browser-rendered sans-serif. The bottom is Gibson. The sans-serif is trying to be the right font-weights, but sans-serif isn't designed for our desired font weights, which is making everything that's "semibold" look unattractive and less readable (i.e. the only thing doing the headers justice is the fact that they're a large font size. At a smaller size they'd be unreadable).

**Comment by mehulkar** [comment]
this is fixed now.
