### ISSUE TITLE
cities take a long time to show up on /cities page

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#362]
I don't know why, but it takes a few seconds to render. Enough time that I, as a user would start clicking around. 

We should either show a spinner for the load time or figure out why it's slow and fix that.

**Comment by jermspeaks** [comment]
There should either be some query parameters or a separate API for this. It's returning everything city, approved and unapproved (see: brew_status). The pain point is calling `Cities.all` in `Cities#index`.

**Comment by mehulkar** [comment]
this was fixed by cache counter in 9c1582a
