### ISSUE TITLE
Redirect to sign up should remember referral page and redirect back

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#363]
non signed in users get redirected to sign up all the time. 
They should be redirected back to where they came from after signing up.

**Comment by ankitshah811** [comment]
@mehulkar where do we stand on this?

**Comment by mehulkar** [comment]
I should be able to do this tonight as well. Note to self:
https://github.com/plataformatec/devise/wiki/How-To:-redirect-to-a-specific-page-on-successful-sign-in


------
Mehul Kar
@mehulkar

**Comment by ankitshah811** [comment]
bump @mehulkar
