### ISSUE TITLE
Waitlisted users cannot sign into their accounts after being logged out

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#375]
Even though there's no sign out link for new users, they could delete cache or something to get logged out, after which they can't return.

![screenshot 2015-05-18 14 43 49](https://cloud.githubusercontent.com/assets/1022843/7691073/70820de6-fd6c-11e4-92f4-d82376b97055.png)

**Comment by nickbarnwell** [comment]
it should be `forbes_city_path`

**Comment by nickbarnwell** [comment]
This *is* `forbes_city_path` on master. Fixed by  a708496f4b7eecd8e62383de66421da002263524 which I can't even.
