### ISSUE TITLE
Favicon is old and rusty

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#383]
Upgrade to new logo

![fb_yellow](https://cloud.githubusercontent.com/assets/1022843/7707677/d3e2828c-fe05-11e4-871b-e3a2e0e3ad5e.png)

**Comment by nickbarnwell** [comment]
We need a hinted 16x16 and 32x32px version as well as a 156px png version for everywhere else.

**Comment by mehulkar** [comment]
this is fixed now, i think.
