### ISSUE TITLE
admin/overview and admin/overview/users don't load

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#386]
Loads of data that take too long to populate, so the site returns an error every time

**Comment by ankitshah811** [comment]
![screen shot 2015-05-19 at 11 49 59 am](https://cloud.githubusercontent.com/assets/1022843/7711112/3c524a16-fe1d-11e4-9bfa-ef2d366a29b4.png)

**Comment by nickbarnwell** [comment]
we have a 30s timeout it takes too long just learn sql <3
