### ISSUE TITLE
Local leader progress bar is static

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#387]
Right now looks like every city has a local leader which is false 
Don't know what the variable to call is

Current:
Leader: `<%= progress_bar(1, 1) %>`
Hosts: `<%= progress_bar(@city.hosts.count, 8) %>`
Attendees: `<%= progress_bar(@city.users.count, 200) %>`

**Comment by nickbarnwell** [comment]
There is none. There was never any clarity on how leaders were going to be tracked or identified in the system and it makes more sense for conversion to convince people it's already in place, ergo it's always true.
