### ISSUE TITLE
Change `city.header_bg` on `/cities` to `small`

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#394]
just realized that on `/cities`, the full size images are being shared

If you see `city.rb`, all header_bg have three sizes, `banner`, `medium`, and `small`. On `/cities`, none of those are being applied, so it renders images completely full size. They aren't even full size on the city pages themselves, where they are actually banners! They're rendered as `medium`

`cities.js:45` is where the `city.header_bg` is referenced, but I don't know the syntax to ensure it calls `small`

can someone take care of this? @mehulkar @jermspeaks

**Comment by mehulkar** [comment]
the api is serializing an address I think. So the solution is to serialize the correct URL. I'd recommend doing it in the CityOverviewSerializer. @jermspeaks want to put in the patch?

**Comment by ankitshah811** [comment]
If you look at `_city_banner.html.haml`, the backgrounds are referenced as such:```- content_for :page_styles do
  :css
    .landscape-header.city {
      background-image: url(#{@city.header_bg.url(:banner)});
    }
    @media only screen and (min-device-width: 320px) and (max-device-width: 568px), (max-width: 800px) {
      .landscape-header.city {
        background-image: url(#{@city.header_bg.url(:medium)});
      }
    }```

In `cities.js:45`, is it as simple as adding `(:small)` here?
```var cityDiv = '<div class="city"><div class="city-image" style="background: url('+city.header_bg+') no-repeat 50% 50%; background-size: cover;"><h2 class=" city-name">' + cityLinkBg(city) + cityLink(city) + '</h2></div></div>';```

**Comment by jermspeaks** [comment]
Most likely, it could be added in the `+city.header_bg+` portion of your CSS style if you're adding a slug at the end of the url.

**Comment by mehulkar** [comment]
@ankitshah811 no, wec can't just add `(:small)` to the js file. the `(:small)` is an argument to a ruby method on server side pages. In the js file, `.header_bg` is a property on the JSON response we're getting from the API. So `(:small)` doesn't make sense there.

**Comment by mehulkar** [comment]
Closed by #396
