### ISSUE TITLE
request to /self/interests on page load

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#402]
Some JS is makes this request on every page load. Not sure why or where. Even for unauthenticated users. (which is fine since it gets redirected).

**Comment by jermspeaks** [comment]
`GET /api/v1/users/self/interests HTTP/1.1`

Looks like this is the culprit. 
```js
	$.get('/api/v1/users/self/interests', function(user_info) {
		if (user_info.leading) {
			leading_button.addClass('applied');
		}

		if (user_info.hosting) {
			hosting_button.addClass('applied');
		}

	});
```

```js
var fns = [onCitiesIndexLoad, onCitiesShow];

fns.forEach(function(e, i) {
	$(document).ready(e)
	$(document).on('page:load', e)
});
```
I think you want to add a conditional only to make it run on the appropriate page, like this.

```js
if (window.location.pathname.indexOf('cities/') >= 0) { /* do something */ }
```

**Comment by mehulkar** [comment]
yeah i think that is appropriate. not entirely sure which page it's supposed to be active on though. do you know for sure it's the /cities/ page? If so, the function right above (onCitiesIndexLoad) is doing the same check.

**Comment by ankitshah811** [comment]
It's supposed to be active on `/cities`, any new city page, and `/hosting`. 

When new `/profile` pages are clearly designed, it would likely be called there as well.
