### ISSUE TITLE
Create an admin display to see tea time information

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#407]
Would love to be able to create a clean table display (and/or download a CSV to do this) to see tea time info across the following criteria:

1. Date range
2. Host
3. City
4. Attendance
   * Full (5 `pending` if attendance not marked or 5 `attended`), Waitlist (≥1 `waitlist`), semi-full (3-4 `pending` or `attended`), small (1-2 `pending` or `attended`) or empty (0 `pending` or `attended`)
 
I imagine it would output the following:

| City Name | TT Date | TT Start Time | TT Host | TT Location | Unconfirmed Attendance Count (`pending`) | Attendance Count (`present`) | Canceled Attendance Count (`flake`) | No Show Count (`no_show`) | Waitlist Count (`waiting_list`) |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

**Comment by ankitshah811** [comment]
This would be useful for a few things, and I imagine it would actually be best bundled into the admin dashboard we've talked about for far too long.

For now, I do have an immediate interest in being able to see the tea times of the last month in this format, as I have a little bit of host outreach to do regarding the last few weeks of website confusion and lackluster tea time attendance. @mehulkar or @nickbarnwell, could one of you fire me a note with the the command to source and download this information from the last month into a CSV?

**Comment by mehulkar** [comment]
we have this now.
