### ISSUE TITLE
Command to release users from waitlist

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#408]
After we have host pages, tea times, and user profile management (`profile` and `/user/.../`) redesigned for the new site, it seems like it would behoove us to turn off the waitlist feature. We're not driving user counts that warrant it, and it blue balls new users while taking away potential attendees from our tea times. 

Right now, we need a barebones interface to release users from the waitlist. Right now, a user's priority level is determined by sign up time, so earlier sign ups get off waitlist sooner than later ones. 

However, the waitlist capacity is a good one, and we should ideally have a switch that allows us to put new users on waitlists if ever we do get a burst that we can't handle.

![waitlist release spec](https://cloud.githubusercontent.com/assets/1022843/7800514/38fbd442-02cb-11e5-809c-bc21235435d2.png)

Waitlist release spec sketch file: https://www.dropbox.com/s/nwyqloue5joo7rx/Waitlist%20Release%20Quick%20Spec.sketch?dl=0

**Comment by ankitshah811** [comment]
Similar to #407, this would be likely best bundled into the admin dashboard.

For now, I do think we should be able to immediately release a number of users in our active cities off waitlists. @mehulkar or @nickbarnwell, could one of you fire me a note with some instructions on how to change users' statuses to being active? And instead of building a janky email trigger right now, just allow for a CSV to be exported (per city) and I can email them directly with Mailchimp. 

I will spend some time after handling designs and implementation for #349 working on admin dashboards and capacities (more functionality and needs, less design / UI)

**Comment by mehulkar** [comment]
we'll do this manually for now. admin section needs revisiting anyway. after #438 users are no longer being waitlisted.
