### ISSUE TITLE
Host change emails coming in twice

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#414]
Upon changing the host for a tea time, the email comes in twice. It also references the tea time by the new host instead of the old one, making it a little nonsensical for the new host (seems like the new host was the host all along).

Going to dive in and try to fix markup and formatting, but don't know why it's coming twice. See two screens below:

1.
![screenshot 2015-05-27 10 15 19](https://cloud.githubusercontent.com/assets/1022843/7842883/f039e69a-045a-11e5-9165-d3afae595c8b.png)

2.
![screenshot 2015-05-27 10 15 37](https://cloud.githubusercontent.com/assets/1022843/7842882/f03a7eca-045a-11e5-9a6e-8fd0d666318b.png)

**Comment by nickbarnwell** [comment]
They clicked the form submit twice
