### ISSUE TITLE
bad signin takes you to old sign in page

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#444]
Probably a Devise internal that takes you to a certain route (sign_in_path) or something maybe? if you sign in with bad credentials, it will take you to the old styles

**Comment by ankitshah811** [comment]
@mehulkar I think this is still happening on http://teawithstrangers.com/ right now

**Comment by mehulkar** [comment]
Yeah it is :/. It's fixed in master though, needs to be deployed.

On Sunday, June 7, 2015, Ankit Shah <notifications@github.com> wrote:

> @mehulkar <https://github.com/mehulkar> I think this is still happening
> on http://teawithstrangers.com/ right now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeaWithStrangers/tws-on-rails/issues/444#issuecomment-109819108>
> .
>


-- 

------
Mehul Kar
@mehulkar

**Comment by ankitshah811** [comment]
Oh ok! Wasn't sure if you thought you fixed it and it was still broken. All
good :)

**Comment by mehulkar** [comment]
I did think I fixed it and deployed. But then I fixed it again and didn't
deploy.

On Sunday, June 7, 2015, Ankit Shah <notifications@github.com> wrote:

> Oh ok! Wasn't sure if you thought you fixed it and it was still broken. All
> good :)
>
> On Sun, Jun 7, 2015 at 5:55 PM, Mehul Kar <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Yeah it is :/. It's fixed in master though, needs to be deployed.
> >
> > On Sunday, June 7, 2015, Ankit Shah <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > @mehulkar <https://github.com/mehulkar> I think this is still
> happening
> > > on http://teawithstrangers.com/ right now
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/TeaWithStrangers/tws-on-rails/issues/444#issuecomment-109819108
> > >
> > > .
> > >
> >
> >
> > --
> >
> > ------
> > Mehul Kar
> > @mehulkar
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/TeaWithStrangers/tws-on-rails/issues/444#issuecomment-109819308
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeaWithStrangers/tws-on-rails/issues/444#issuecomment-109820012>
> .
>


-- 

------
Mehul Kar
@mehulkar
