### ISSUE TITLE
tea times on city page are aligned weird

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#447]
the fix might have gotten lost in commits somewhere. (this is in prod right now)

![screen shot 2015-06-03 at 1 56 37 am](https://cloud.githubusercontent.com/assets/490968/7956287/d07642e8-0993-11e5-9f34-81c4cb4f254f.png)

**Comment by nickbarnwell** [comment]
The problem is when people set long locations. @ankitshah811 do you want to truncate and reveal on mouseover or something? There's no simple fix with CSS

**Comment by ankitshah811** [comment]
@nickbarnwell @mehulkar Not sure what the best sol'n would be at the moment. Thinking on it though.
