### ISSUE TITLE
fix URLS from /:cityname to /cities/:cityname

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#448]
/:name is bad. we should redirect for now and then remove those routes all together. 

not too hard to find cities if people use old links since the cities index page is front and center in the nav.

**Comment by ankitshah811** [comment]
why is `/:name` bad? I think we migrated towards that because city pages were actually the most common place for someone to go on tws, so it makes sense to keep these urls as memorable as possible

**Comment by mehulkar** [comment]
/:name is bad because it's only a wildcard. So for example, if someone
rearranged the routes file to put that route definition at the top,
teawithstrangers.com/about will also match it and will be routed like a
city page (and crash because no city named "about" will be found).

I guess it's not terrible. We can keep it if you think that's better and
add some test cases around it and redirect to /cities if the city isn't
found. Feel free to close this if you think /:cityname is better!


------
Mehul Kar
@mehulkar
