### ISSUE TITLE
Hosts Can Take Attendance after a Tea Time

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#45]
A view in the hosts' admin panels for them to mark status on attendees (akin to 
![host-post-tea](https://cloud.githubusercontent.com/assets/1022843/3108087/7b074026-e68c-11e3-807c-c4ca0b096e47.png)

For hosts to mark attendance and prompt them to send a follow up email to the group

**Comment by mehulkar** [comment]
i think this is implemeted
