### ISSUE TITLE
thoughts on homepage copy

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#451]
Under "So why are thousands of people don't it", I see three sections. 

Currently the headers are

- "It's weird."
- "We won't meet otherwise."
- "Your hands are made for high fiving!"

I propose changing them to:

- "It's weird.
- "It's manufactured serendipity"
- "It's real"

Reasons:

- the repetition of "it's" is more memorable and recitable when people tell their friends.
- "manufactured serendipity" is a great phrase and it could be front and center
- "it's" real is the last thing people will see as they scroll down and it hits hard. 

The copy would have to change slightly for the second and third, but that's manageable. I can propose that as well.

**Comment by ankitshah811** [comment]
No rush, but would love proposals on copy for 2nd and 3rd before I take a stab at it. 

The site overall has my voice smothered all over it, and that works decently well, but I'd love to start entertaining new tones/voices/word choices

**Comment by mehulkar** [comment]
What do you think of this:

```
It’s weird.

Open minds are a prerequisite around here. Everyone at tea
time is stepping a little out of their comfort zone. But the
more you think about it, it's weird that that's weird. Right??

-------

It's "manufactured serendipity".

Tea time is all about bumping into someone outside a bookstore.
Or meeting someone's gaze in a crowded train. Or being at the
same concert in the same section at the same time. Except without
the bookstore and the train and the concert.

-------

It's Real.

Seriously. Real humans are sooo much cooler than their tweets.
A hi five is so much better than a Facebook like. At tea time,
you'll get to see me before I apply the Nashville filter on Instagram.
```
