### ISSUE TITLE
users attending teatime don't get registration email

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#455]
- [ ] call `send_mail` method when attendance is created (it already contains all the biz logic for what email to send based on waitlisting,pending, etc)
- [ ] Change attendance/registration name to attendance/confirmation (registration sounds like user sign up and is confusing)

**Comment by ankitshah811** [comment]
@mehulkar thanks so much for taking the time to break down this problem into actionable steps. could you offer a sense of how large in scope these tasks are? have no idea if this is a lot or no

**Comment by mehulkar** [comment]
~1hr work, I would think.
