### ISSUE TITLE
Rejected cities show up on /cities page

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#466]
I have since deleted the city, but upon rejection, it showed up here (but status was rejected on `/admin/overview/cities`

![screenshot 2015-06-10 13 44 16](https://cloud.githubusercontent.com/assets/1022843/8093607/ee026826-0f76-11e5-9e78-dca5c055ea01.png)

**Comment by mehulkar** [comment]
Fixed in #469
