### ISSUE TITLE
City suggestion related emails not going out

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#467]
I tried submitting a city, and I then rejected it via admin panel and I didn't get the `notify_city_suggestor` emails. I also don't see any email in the code to acknowledge city suggestors (i.e. the one that says "we got your suggestion and will get to it").

**Comment by mehulkar** [comment]
This should be going out, i just tested and it worked. It's possible that the app crashed because of memory consumption. We might have made this a little better in 513d131ab3281879a5e31f8f7d35d5df6394901e.

**Comment by ankitshah811** [comment]
close this shit 18 days ago @mehulkar !!
