### ISSUE TITLE
rejection email issues

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#473]
- [x] tense correction
  - "We only do this when we can’t figure out where this city was"

    should be
  
    "We only do this when we can’t figure out where this city _is_"
- [x] bleep, bloop sign off needs line break (add two trailing spaces to bleep bloop line)

**Comment by ankitshah811** [comment]
Yo did you already handle this or pending for me to take care of?

**Comment by mehulkar** [comment]
no did not handle it. the issue would be closed if i had handled it :p


------
Mehul Kar
@mehulkar

**Comment by ankitshah811** [comment]
close this shit dummy

**Comment by ankitshah811** [comment]
CLOSE IT 13 DAYS AGO
