### ISSUE TITLE
signup page is missing some padding

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#492]
also probably broken from last night. not a huge deal. should be straightforward to fix

**Comment by mehulkar** [comment]
also login page.

**Comment by ankitshah811** [comment]
Weird, is there a specific file that has these styles that led to them being lost? Or are there a whole slew of changes that were lost?

**Comment by mehulkar** [comment]
only saw these two pages as obviously problematic. Clicking around didn't see anything majorly unsightly, but we already know how perceptive I am when it comes to design :p

**Comment by mehulkar** [comment]
fixed by fb32cf08b106a8a8b2d12366c9cd4d115b0e7a6d
