### ISSUE TITLE
Copy Email workaround spec

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#504]
An alternative to a flash-based copy emails button

This is a proposal for group email copy behavior. Not individual email addresses. That will come later, when we're in a position to tackle 'expanded view' of attendees*

![copy group emails spec](https://cloud.githubusercontent.com/assets/1022843/8504697/b4764ebc-218a-11e5-9698-89b78a69f6e1.png)

*expanded view mentioned above is this (hasn't been updated to reflect updated attendee list styles that are shown in above screen): 

<img width="453" alt="screen shot 2015-07-03 at 1 54 06 pm" src="https://cloud.githubusercontent.com/assets/1022843/8504716/0f051084-218b-11e5-8bae-3e87c3cce58b.png">

**Comment by mehulkar** [comment]
yeah, this is what i was going to propose as well.
