### ISSUE TITLE
/assets/missing.jpg not found

### ISSUE THREAD

**Issue by jermspeaks** [TeaWithStrangers/tws-on-rails#516]
The missing.jpg assets couldn't be found when I logged in without an avatar. Do we have a placeholder for this?

**Comment by mehulkar** [comment]
do you know what page were you on when it 404'd? not sure if a placeholder is in place, but it could be that it's just looking in the wrong place. if it's not, @ankitshah811 can provide a placeholder image.

**Comment by jermspeaks** [comment]
Under the `/users/edit` route, for profiles without a picture.

**Comment by mehulkar** [comment]
Nice. A PR would be super appreciated to fix that! Either the image deosn't exist, or its' looking in the wrong place for it

**Comment by ankitshah811** [comment]
Don't think there is one. I'll whip one up in the next week
