### ISSUE TITLE
Attendance mailer emails are going out multiple times

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#518]
Not sure if this is an issue for other emails as well, but numerous hosts (including myself) have been getting the same "Add your tea time to calendar" and "Mark attendance" emails several times over. It's been very unusual. 

One case:

> I was perusing my TWS dashboard, and I realized that I had not checked the "All Sent!" box after sending my thank you emails for a tea time 3 weeks ago, so I checked the box now. This, for some reason, caused two emails to be sent to me: one telling me to add the Tea Time to my Google Calendar (so presumably, the system thought I had just created the tea time, for some reason), and a second one, telling me to mark attendance (presumably, the system realized the date/time of the tea had passed, and so sent me the automated email that happens at the end of the tea.)

Another: 

> On 7/7, the day of my tea time that was set up a week earlier, I got 3 Add to Calendar emails (6:24am, 12:44pm, 12:44pm). On 7/8, I got 2 emails at 2:54pm and 1 at 4:14pm to Add My Tea Time from 7/7 to my calendar. At the same times + frequencies, I got the emails to Mark Attendance. The day after the tea time. 6 emails. And today, 7/9 at 12:34pm, I got 2 more iterations of both the Mark Attendance email and Add to Calendar for the same 7/7 email without setting up anything new.

Another:
![qstlonpy7gutj9dth3fmha_2izxxfrvsnscwpl0-jvk](https://cloud.githubusercontent.com/assets/1022843/8610284/05cbec52-2665-11e5-83c6-5b5230fcdd76.png)

**Comment by nickbarnwell** [comment]
It's because `after_create` was changed to `after_commit`. Whenever any edit happens to the tea time (e.g. change of status) it requeues those emails.
