### ISSUE TITLE
Hosts cannot make profile edits right now

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#528]
The `/profile/host_profile` page was separated from `/users/edit` on our most recent sprint, but I didn't realize that (1) the forms aren't prefilled with the host's information and (2) in the case a host is trying to make edits from square one (i.e. they go from blank form to manually filling it out), any changes can't be saved because it produces the error 'Current password can't be blank' on `users/edit`

- [x] Passwords shouldn't be required to make profile edits
- [x] The host profile edit page should be prefilled with the host's profile content

**Comment by mehulkar** [comment]
now they can.
