### ISSUE TITLE
Add notification for users that have expressed interest in becoming a host 

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#550]
Branch off of this #548 to create a notification for attendees that have expressed interest

**Comment by skeller88** [comment]
+1. Also would be nice to have some UI when they click "you're interested" like "Thanks for signing up. You should receive an email confirmation."

**Comment by mehulkar** [comment]
@ankitshah811 changed your comment to point to the PR isntead of the commit. (Sometimes commit shas change)

@skeller88 the UI currently changes the button from "I'm Intested" to some confirmation. It's not the most explicit, but _something_ does exist, just fyi.

**Comment by ankitshah811** [comment]
@mehulkar @skeller88 pushing an update to this later tonight. worked on something when I didn't have internet, so wasn't able to pull this branch and update appropriately, but will be back in code mode tonight to get that done

**Comment by ankitshah811** [comment]
#548
