### ISSUE TITLE
Add rtf to profile editing 

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#551]
Features that would be helpful —

* making URLs clickable
* making text hyperlink-able
* bulleted lists
* bolding text
* italicizing text

**Comment by mehulkar** [comment]
which fields need rtf editing? check all that apply:

- [ ] intro
- [ ] what's your story
- [ ] what might we talk about
- [ ] random sentence

**Comment by ankitshah811** [comment]
Added note: This week, I will be speccing out a new profile editing interface that involves a slew of new fields for profiles that will allow hosts to flex more control around what sorts of content their profiles display (quick version: random carousel of questions that hosts can answer on their profiles with suggested word counts). If this is something that bears implications on how you go about implementing rtf editing (e.g. creating a easy-to-use hook that allows for rtf to be applied en masse while textareas that require rtf formatting grow more common), then wanted to note it here

**Comment by mehulkar** [comment]
Done in #585
