### ISSUE TITLE
Hosts cannot change their profile picture

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#552]
when a host tries to change their photo and save profile, it doesn't work. @mehulkar is this fix relevant to the params here (https://github.com/TeaWithStrangers/tws-on-rails/commit/d0048fcd6793816484104137823019705b91277a#commitcomment-12161672)?

**Comment by mehulkar** [comment]
yes, possible due to the permitted params. i can look into it late tonight
or tomorrow to diagnose.


------
Mehul Kar
@mehulkar

**Comment by ankitshah811** [comment]
@mehulkar updates?

**Comment by mehulkar** [comment]
fixed and deployed hot patch


------
Mehul Kar
@mehulkar
