### ISSUE TITLE
Customized reminder emails markup is looking trippy

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#580]
I don't know what's going on here, but I think the way attachments are rendering all this gibberish @mehulkar 

<img width="1085" alt="screen shot 2015-07-24 at 5 44 10 pm" src="https://cloud.githubusercontent.com/assets/1022843/8885236/b7f2a4bc-322b-11e5-834a-0326f9186474.png">

**Comment by mehulkar** [comment]
Woah weird. May be able to check it out this weekend. I tested in mail
catcher and it seemed fine to me.

On Friday, July 24, 2015, Ankit Shah <notifications@github.com> wrote:

> I don't know what's going on here, but I think the way attachments are
> rendering all this gibberish @mehulkar <https://github.com/mehulkar>
>
> [image: screen shot 2015-07-24 at 5 44 10 pm]
> <https://cloud.githubusercontent.com/assets/1022843/8885236/b7f2a4bc-322b-11e5-834a-0326f9186474.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeaWithStrangers/tws-on-rails/issues/580>.
>


-- 

------
Mehul Kar
@mehulkar

**Comment by ankitshah811** [comment]
Yah that was annoying because mail catcher didn't produce any issues but three examples of emails sent to me show this bug



—
