### ISSUE TITLE
Organize hosts in grid in a way that puts most active hosts first

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#599]
Only show hosts who have hosted a tea time in the last 8 weeks

**Comment by mehulkar** [comment]
this will probably involve some sort of introspection into the host's activities, so we know what we want to sort by. Could start simply with # of tea times

**Comment by ankitshah811** [comment]
I'd like for it to involve some combination of # of tea times and recency of tea times. Will ponder further
