### ISSUE TITLE
@mehulkar make your profile less ridiculous

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#635]
<img width="475" alt="screen shot 2015-08-13 at 1 14 51 pm" src="https://cloud.githubusercontent.com/assets/1022843/9256456/79a2864a-41bd-11e5-840b-f6b08e609ef2.png">

**Comment by mehulkar** [comment]
wontfix.

**Comment by ankitshah811** [comment]
-_-



—
