### ISSUE TITLE
Can I learn to develop for TWS?  via dgretton@mit.edu

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#637]
**From:** dgretton@mit.edu<br>
**Subject:** Can I learn to develop for TWS?<br>
**Date:** August 16, 2015 at 03:47PM<br>
Hi Tech@tea!Pleased to meet you! I decided I'd like to try to join the tech team for TWS, learn to help with website maintenance, etc. I really care about TWS and I also want to learn how to make this exact kind of project for some future stuff I have in mind. I'm a CS student in my senior year, I have lots of programming experience, startups, some Apple iCloud work, but not web stuff. I'd especially like to meet with one or (preferably) 2+ of you (more the merrier! and I wanna meet you!) before I leave to go back to school on the 27th of August, maybe do a (2? 3 hr?) crazy-pace crash course if you're up for it. Do you think I could set something up with you in the coming 2 weeks? Thanks guys, I really hope I can be helpful :) Dana<br>
: http://ift.tt/19fNRe4<br>
cc/ @mehulkar, @ankitshah811, via tech@tws email

**Comment by mehulkar** [comment]
will continue over email.
