### ISSUE TITLE
Hosting: I'm Interested Button Doesn't Work

### ISSUE THREAD

**Issue by Datamine** [TeaWithStrangers/tws-on-rails#643]
Using Firefox 33.0 for Linux Mint, the *I'm Interested* button on http://www.teawithstrangers.com/hosting doesn't do anything, it merely takes you back to the top of the page.

**Comment by ankitshah811** [comment]
John, when you refresh the page after hitting that button, does it display
the 'Thanks for being interested' div?

**Comment by ankitshah811** [comment]
It should look like this.

<img width="717" alt="screen shot 2015-09-02 at 10 56 24 am" src="https://cloud.githubusercontent.com/assets/1022843/9634780/4605c5f0-5161-11e5-84e3-23129165c6dc.png">

**Comment by Datamine** [comment]
I accessed the page just now, and now I'm seeing that div (I did not hit the button and did not refresh). That's strange -- I hadn't seen it before.

**Comment by ankitshah811** [comment]
Hmm, interesting. If you didn't hit the button, what was it that wasn't working?



—
