### ISSUE TITLE
Tea time notes don't display line breaks

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#649]
@mehulkar I think at one point you told me what the solution to this was, but I can't seem to find it anywhere. Will stackoverflow to rediscover, but if you see this and can share here, would be helpful

Notes are being rendered here: https://github.com/TeaWithStrangers/tws-on-rails/blob/master/app/views/profiles/_teatime_info.html.erb#L40

**Comment by mehulkar** [comment]
I don't remember what I said before, but you might look into CSS `line-break` or `white-space` properties.

https://css-tricks.com/almanac/properties/w/whitespace/

https://developer.mozilla.org/en-US/docs/Web/CSS/line-break

**Comment by ankitshah811** [comment]
I think it was something about the `erb` syntax. Something that would be written in the markup that rendered the text as it was entered in the `textarea`. Kinda like this: https://github.com/TeaWithStrangers/tws-on-rails/blob/master/app/views/hosts/show.html.erb#L61. Maybe that itself (`simple_format`) was the solution? Can't recall

**Comment by mehulkar** [comment]
no, sorry, i'm not familiar with that. I've never used simple_format


------
Mehul Kar
@mehulkar

**Comment by nickbarnwell** [comment]
Replace all \n in the host text with `<br/>` might actually work there, but it's a big hack

**Comment by ankitshah811** [comment]
@nickbarnwell you mean in the input that the hosts write? Is there a simple script that can be written to do this for the hosts? Or would your suggestion require users to do that themselves?
