### ISSUE TITLE
Attendance related emails are sending at the wrong times

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#661]
Report from the user:
> I went for the tea with strangers on Sunday and it was really good fun. I'm writing because it kinda sounds like this e-mail should be sent before the tea and I got it after. I also got the Google calendar invite on Monday (the day after the tea) so I don't know if it's a bug or something but I figured I'd alert you to that :)

<img width="618" alt="screen shot 2015-11-11 at 11 57 57 am" src="https://cloud.githubusercontent.com/assets/1022843/11101396/8daa4f20-886b-11e5-8197-091e482c8d4e.png">

**Comment by nickbarnwell** [comment]
Sendgrid account fell over because my CC was stolen and I forgot to update the billing info there. Any emails that failed over the weekend weren't sent.
