### ISSUE TITLE
Re: My Host Time Isn't Showing!  via noumoua03@gmail.com

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#664]
**From:** noumoua03@gmail.com<br>
**Subject:** Re: My Host Time Isn't Showing!<br>
**Date:** November 20, 2015 at 12:13PM<br>

Ooooh, I had no idea! Why is it set up that way? Just wondering...

On Fri, Nov 20, 2015 at 12:12 PM, Ankit Shah  wrote:

Hey! If it's set for more than 2 weeks from now, it will only show up when the tea time is within a two week window. 

On Fri, Nov 20, 2015 at 8:47 AM, Nou Moua  wrote:

Hi!

I posted a tea time and it's not showing up on the website :( It is on my dashboard though. Not sure what was going on + tested it on Chrome and Safari browser + cleared my cache in case it wasn't refreshing... and still no luck :(

Any assistance is greatly appreciated!

Cheers,

Nou

<br>
: http://ift.tt/19fNRe4<br>
cc/ @ankitshah811, via tech@tws email

**Comment by nickbarnwell** [comment]
It was set up this way because that was what was specced last May! Easy to change, we should look at the average volume of tea times for each city and alter it a bit, perhaps

**Comment by ankitshah811** [comment]
@nickbarnwell good call, will make a point to derive some insights from the data analysis to inform this decision
