### ISSUE TITLE
City Page: Having 0 tea times leaves box where tea times appear

### ISSUE THREAD

**Issue by nickbarnwell** [TeaWithStrangers/tws-on-rails#665]
![](http://dl.dropbox.com/u/9061771/Screenshots/-yc3.png)

**Comment by ankitshah811** [comment]
thanks for pointing this out. that box is the 'home city indicator' (i.e. says what your home city is if not the current city page / offers option to select home city if you haven't set one yet). should be wrapped in a `if user?` conditional. will fix!
