### ISSUE TITLE
Don't show `unapproved` `rejected` cities in city dropdown for new host form

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#680]
`/admin/host` has a cities list that includes >1000 cities. Hugely distracting. Lots of repeats,which created problems. This should be fixed ASAP.

@nickbarnwell or @mehulkar, think this should be a 2min fix, as we already have ways to filter which cities are visible in other dropdowns. Chances you could do this in spare time sometime this week? 

Onboarding lots of new hosts lately, and this adds a solid 2-3min of work and another 2-3min of annoyance every single time I pick the 6th repeat of London instead of the actual instance, have to ghost my way into a new host account, set their city properly with the dropdown on `/users/edit`, log out, log back into admin, and repeat

**Comment by mehulkar** [comment]
sorry dude, I am not able to do this.
