### ISSUE TITLE
/profile link in substitute host email is broken

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#685]
<img width="556" alt="screen shot 2016-04-15 at 11 14 20 am" src="https://cloud.githubusercontent.com/assets/1022843/14570859/3b3750ca-02fb-11e6-84c2-6fbac255bb94.png">

Link is currently directed to `profile` instead of `http://teawithstrangers.com/profile`

**Comment by nickbarnwell** [comment]
This got fixed by #684. Closing.
