### ISSUE TITLE
Waitlist copy issue

### ISSUE THREAD

**Issue by jtilton** [TeaWithStrangers/tws-on-rails#687]
Weird copy:
![image](https://cloud.githubusercontent.com/assets/1581186/16255689/d075d2d0-3800-11e6-8609-a29c1d6b35c6.png)

Code [here](https://github.com/TeaWithStrangers/tws-on-rails/blob/2d3faa8876b7a394c85636230e833caa6489ce1e/app/views/profiles/_teatimes_on_waitlist.html.erb#L23-L24)

**Comment by nickbarnwell** [comment]
Looks like this was fixed by db8832fe0fbd4137d7a866e41de35e5b7a15dd08
