### ISSUE TITLE
Group Hosts by Activity on City Pages

### ISSUE THREAD

**Issue by nickbarnwell** [TeaWithStrangers/tws-on-rails#696]
- [x] Active Hosts Display Photos
- [x] Legacy Hosts display as a name
- [x] Inactive Hosts are Hidden

**Comment by nickbarnwell** [comment]
![screen shot 2016-11-25 at 14 52 43](https://cloud.githubusercontent.com/assets/380810/20636277/dd195dba-b31e-11e6-98c2-9ce772ea9fd3.png)

**Comment by ankitshah811** [comment]
Addressed by #707
