### ISSUE TITLE
Host profile photo upload limit

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#727]
Just created a new host http://www.teawithstrangers.com/cities/SF/host/19879
Original photo they submitted for their profile was 4.2mb. Hit an Application Error
Shrunk photo to 1.8mb. Still got an error.
Uploaded profile with no photo. No error. 

Then, #728 happened. Not sure if they're related issues though.

**Comment by nickbarnwell** [comment]
They're related. Everything should work now; record wouldn't save because of failing validation on the `commitment` column of the `HostDetail` object. Should be fixed as of #731. I can't upload Ankhi's photo because I don't have the file - will email her and see if she can update.
