### ISSUE TITLE
Can't access /profile from new host account

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#728]
After creating this new host http://www.teawithstrangers.com/cities/SF/host/19879 (see #727), I tried to ghost into their account so I could give the profile photo upload another shot. 
Upon submission on `/admin/ghost`, I was redirected to `/profile` which gave me a 404. 

Also noticed a 500 on `/cities/SF` and `/SF`. 

I don't get the same 404 when I'm on my personal account on TWS, but I do get the 500s on `/cities/SF` and `/SF` (not on any other city page though)

**Comment by nickbarnwell** [comment]
Fixed in #731
