### ISSUE TITLE
NYC page getting a 500

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#732]
Flagged by Vighnesh. New NYC host whose profile I uploaded to the website yesterday afternoon. Issue not consistent with any other city page, leading me to believe it has something to do with a new host on the page.

![2018-03-13 at 12 02 pm](https://user-images.githubusercontent.com/1022843/37363984-7e1a98e4-26b6-11e8-8347-45c20cda3ef8.png)

**Comment by nickbarnwell** [comment]
Never ran migrations for #731 so commitment never got set…should be fixed now and into the future.
